name: 01 - Continuous Integration (Sample Application)
on:
  pull_request:
    branches:
    - main
    paths:
    - 'applications/sample-application/**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and lint Bicep
      run: |
        az bicep build --file applications/sample-application/application.bicep